name: DevOps Demo

on: 
  push: 
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checckout@v4

      - name: Build Project
        run: echo "Build Successful"

      - name: Test Project
        run: echo "Test successful" 
  
